version: '3'
services:
  aws:
    image: munihemanth/aws:latest
    ports:
      - "8000:80"
    deploy:
      replicas: 3

  devops:
    image: munihemanth/devops:latest
    ports:
      - "8001:80"
    deploy:
      replicas: 3

  azure:
    image: munihemanth/azure:latest
    ports:
      - "8002:80"
    deploy:
      replicas: 5

  datascience:
    image: munihemanth/datascience:latest
    ports:
      - "8003:80"
    deploy:
      replicas: 5
